# Generated by Django 3.0.5 on 2020-04-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('seller_phone', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='restaurant_image')),
                ('restaurant_status', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='menu_image')),
                ('menu_price', models.FloatField()),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=200)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.restaurant')),
            ],
        ),
    ]
